title: DEV Sandbox Configuration
http:
  port: "8081"
  
salesforce:
  port: "8081"
  basepath: "/"
  timeout: "120000"
  protocol: "HTTP"
  username: "satya.devfull@summittech360.com"
  password: "2bMore$ecure"
  securityToken: "Vv1L7LxhP0XS1UkvzxzCMhgD9"
  basicAuthEndpoint: "https://test.salesforce.com/services/Soap/u/50.0"
  consumerKey: "3MVG9XmM8CUVepGZDLbd5VPlTkyoE_muHd9d_ts0fRknosDbB_2d_5g3NpnrxvWgF8Ccq7emg5zEaK15TFHDn"
  consumerSecret: "6B3805F1100DA71CB61DE6AE3F43FF6971C299257B7888B41DE5868695635184"
  authTokenEndpoint: "https://learninga-z--devfull.lightning.force.com/services/oauth2/token"
  clientid: "TestClientId"
  